name: GitVersion Automatic Versioning
on:
  pull_request:
    branches-ignore:
      - 'd4-*'
    types: [closed]
jobs:
  run-gitversion:
    name: Run GitVersion
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      ver: ${{ steps.gv.outputs.semVer }}
      pre: ${{ steps.gv.outputs.commitsSinceVersionSource }}
      shortVer: ${{ steps.gv.outputs.majorMinorPatch }}
      longVer: ${{ steps.gv.outputs.fullSemVer }}
      branch: ${{ steps.gv.outputs.branchName }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Fetch tags and branches history
        run: git fetch --prune
      - name: Setup GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.11
        with:
          versionSpec: '5.x'
      - name: Run GitVersion
        id: gv
        uses: gittools/actions/gitversion/execute@v0.9.11
        with:
          useConfigFile: true
          configFilePath: GitVersion.yml
  run-bump-file-version:
    name: Update and generate files, commit and tag
    needs: run-gitversion
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Find and replace version in README
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: '([0-9]+[.][0-9]+[.][0-9]+){1}'
          replace: ${{ needs.run-gitversion.outputs.ver }}
          regex: true
          include: '**README.md'
      - name: Find and replace version in code
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: '([0-9]+[.][0-9]+[.][0-9]+){1}'
          replace: ${{ needs.run-gitversion.outputs.ver }}
          regex: true
          include: '**.fx?'
      - name: Commit and push changes to current branch
        run: |
          git config --global user.name "FroggEater"
          git config --global user.email "bastien.froment@outlook.fr"
          git commit --allow-empty -am "ci: automatic version update"
          git push
      - name: Tag changes on current branch
        run: |
          git config --global user.name "FroggEater"
          git config --global user.email "bastien.froment@outlook.fr"
          git tag -f -a v${{ needs.run-gitversion.outputs.ver }} -m "ci: automatic tag update"
          git push --force --tags
