name: Changelog Builder
on:
  workflow_dispatch:
  push:
    tags:
      - '*'
jobs:
  run-changelog-builder:
    name: Run Full Changelog Builder
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build changelog
        id: cl
        uses: mikepenz/release-changelog-builder-action@v2.7.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          configuration: 'GitChangelog.json'
          outputFile: 'CHANGELOG.md'
          commitMode: 'true'
          fromTag: 'v0.1.0-rc29'
      - name: Commit and push changes to current branch
        run: |
          git config --global user.name "FroggEater"
          git config --global user.email "bastien.froment@outlook.fr"
          git commit --allow-empty -am "ci: automatic changelog update"
          git push