name: GitVersion Manual Versioning
on:
  workflow_dispatch:
jobs:
  run-gitversion:
    name: Run GitVersion
    runs-on: ubuntu-latest
    outputs:
      ver: ${{ steps.gv.outputs.semVer }}
      shortVer: ${{ steps.gv.outputs.majorMinorPatch }}
      longVer: ${{ steps.gv.outputs.fullSemVer }}
      branch: ${{ steps.gv.outputs.branchName }}
    steps:
      - uses: actions/checkout@v2
      - name: Fetch tags and branches history
        run: git fetch --prune
      - name: Setup GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.11
        with:
          versionSpec: '5.x'
      - name: Run GitVersion
        id: gv
        uses: gittools/actions/gitversion/execute@v0.9.11
        with:
          useConfigFiles: true
          configFilePath: GitVersion.yml
  run-bump-file-version:
    name: Update version in files, commit and tag
    needs: run-gitversion
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find and replace version in files
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: '([0-9]+[.][0-9]+[.][0-9]+(-(alpha|beta){1})?){1}'
          replace: ${{ needs.run-gitversion.outputs.ver }}
          regex: true
      - name: Commit and tag changes to current branch
        run: |
          git config --global user.name "FroggEater"
          git config --global user.email "bastien.froment@outlook.fr"
          git commit -am "version: automatic update"
          git tag v${{ needs.run-gitversion.outputs.ver }}
          git push


